lwc_survey_dynamic_responses/force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwc_survey_dynamic_responses/force-app/main/default/objects/Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <description>Survey question</description>
    <inlineHelpText>Enter the text to display as survey question</inlineHelpText>
    <label>Question Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Question__c/fields/ResponseType__c.field-meta.xml
<CustomField>
    <fullName>ResponseType__c</fullName>
    <label>ResponseType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>checkbox</fullName>
            </value>
            <value>
                <fullName>radiobutton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Responses__c/Responses__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <label>Responses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwc_survey_dynamic_responses/force-app/main/default/objects/Responses__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Responses__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Used to score the survey based on the response</description>
    <inlineHelpText>Enter the response score eg 1,0.5 etc to capture score for the response</inlineHelpText>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Responses__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>captures for selection of the response in the survey</description>
    <inlineHelpText>Selected from the lwc component on survey object</inlineHelpText>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwc_survey_dynamic_responses/force-app/main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Survey Question  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lwc_survey_dynamic_responses/force-app/main/default/objects/Survey_Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Associate the configurable question from the junction object under survey</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Questions</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

lwc_survey_dynamic_responses/force-app/main/default/classes/SurveyController.cls
public with sharing class SurveyController {
    public SurveyController() {

    }

    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuestionList(String ServeyId) {
        System.debug(LoggingLevel.Error,'SurveyId'+ServeyId);
        return [
            SELECT Id, Name,Question_Text__c,ResponseType__c, (Select Id,Name,Score__c,Selected__c from Responses__r) FROM Question__c
             Where Id In (Select Question__c from Survey_Question__c where Survey__c = :ServeyId )  
        ];
    }

    @AuraEnabled(Cacheable=false)
    public static void updateSelectedAnswers(String[] answers) {
        
        set<Responses__c> responses= new set<Responses__c>();
        for(Responses__c res: [Select Id,Name,Selected__c from Responses__c where id in :answers]){
            res.Selected__c = true;
            responses.add(res);
        }
        List<Responses__c> reslist = new List<Responses__c>(responses);
        update reslist;
        
    }
}